version: '3.8'

services:
  # 1. Jenkins: L'orchestratore della Pipeline CI/CD
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true # Necessario per eseguire comandi Docker all'interno di Jenkins
    user: root
    ports:
      - "8080:8080" # Porta web di Jenkins
      - "50000:50000" # Porta per i nodi slave (non usata ora, ma buona prassi)
    volumes:
      - jenkins_home:/var/jenkins_home # Persistenza dei dati di Jenkins
      - /var/run/docker.sock:/var/run/docker.sock # Accesso all'engine Docker HOST
    container_name: jenkins

  # 2. Prometheus: Per la raccolta delle metriche
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # File di configurazione
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090" # Porta web di Prometheus

  # 3. Grafana: Per la visualizzazione delle dashboard
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000" # Porta web di Grafana
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  jenkins_home:
  prometheus_data:
  grafana_data: