global:
  scrape_interval: 15s # Raccogli metriche ogni 15 secondi

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Target della nostra API Sentiment Analysis (Attenzione: usa l'indirizzo Docker Internal)
  - job_name: 'sentiment-api'
    static_configs:
      # L'indirizzo deve essere il nome del container dell'API quando lo eseguiamo in Docker Compose, 
      # ma per ora puntiamo a 'host.docker.internal' che Ã¨ l'IP del tuo host (dove sta girando l'API)
      - targets: ['host.docker.internal:8000']